
// Status
export const TOGGLE_WORK = 'TOGGLE_WORK';
export const RECEIVE_LUNCH_TIME = 'RECEIVE_LUNCH_TIME';
export const RECEIVE_CURRENT_TIME = 'RECEIVE_CURRENT_TIME';
// export const UPDATE_WORK_START = 'UPDATE_WORK_START';
// export const UPDATE_BREAK_START = 'UPDATE_BREAK_START';

// Steps
export const RECEIVE_STEPS = 'RECEIVE_STEPS';

// Weather
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
