// auth
export const AUTHENTICATE = 'AUTHENTICATE';

// db
export const RECEIVE_HISTORY = 'RECEIVE_HISTORY';
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS';

// greylist
export const ADD_URL = 'ADD_URL';
export const REMOVE_URL = 'REMOVE_URL';
export const EDIT_URL = 'EDIT_URL';
export const RECEIVE_GREYLIST = 'RECEIVE_GREYLIST';

// routes
export const SET_ROUTE = 'SET_ROUTE';

// settings
export const SET_WORK_DURATION = 'SET_WORK_DURATION';
export const SET_BREAK_DURATION = 'SET_BREAK_DURATION';
export const SET_LUNCH_DURATION = 'SET_LUNCH_DURATION';
export const SET_SHIFT_DURATION = 'SET_SHIFT_DURATION';
export const SET_START_TIME = 'SET_START_TIME';

// status
export const TOGGLE_WORK = 'TOGGLE_WORK';
export const TOGGLE_PAUSE = 'TOGGLE_PAUSE';
export const TOGGLE_LUNCH = 'TOGGLE_LUNCH';
export const START_WORK = 'START_WORK';
export const START_BREAK = 'START_BREAK';
export const SET_TIME_REMAINING = 'SET_TIME_REMAINING';
export const ADD_FIVE_MINUTES = 'ADD_FIVE_MINUTES';

// tasks
export const RECEIVE_TASK = 'RECEIVE_TASK';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const REMOVE_TASK = 'REMOVE_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';

// weather
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';

// aliases
export const TAB_ALIAS_LOGIN = 'TAB_ALIAS_LOGIN';
export const TAB_ALIAS_SAVE_SETTINGS = 'TAB_ALIAS_SAVE_SETTINGS';
export const TAB_ALIAS_ADD_GREYLIST = 'TAB_ALIAS_ADD_GREYLIST';
export const TAB_ALIAS_REMOVE_GREYLIST = 'TAB_ALIAS_REMOVE_GREYLIST';
export const TAB_ALIAS_EDIT_GREYLIST = 'TAB_ALIAS_EDIT_GREYLIST';
export const TAB_ALIAS_ADD_TASK = 'TAB_ALIAS_ADD_TASK';
export const TAB_ALIAS_REMOVE_TASK = 'TAB_ALIAS_REMOVE_TASK';
export const TAB_ALIAS_COMPLETE_TASK = 'TAB_ALIAS_COMPLETE_TASK';
