
// Status
export const TOGGLE_WORK = 'TOGGLE_WORK';
export const RECEIVE_LUNCH_TIME = 'RECEIVE_LUNCH_TIME';
export const RECEIVE_CURRENT_TIME = 'RECEIVE_CURRENT_TIME';
export const ADD_FIVE_MINUTES = 'ADD_FIVE_MINUTES';
export const HALT_BACKGROUND = 'HALT_BACKGROUND';

// Set Time
export const SET_WORK_DURATION = 'SET_WORK_DURATION';
export const SET_BREAK_DURATION = 'SET_BREAK_DURATION';
export const SET_LUNCH_DURATION = 'SET_LUNCH_DURATION';
export const SET_START_TIME = 'SET_START_TIME';

// Weather
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
